<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite name="TestPawnshopApp-20241019183522" tests="7" file=".py" time="0.005" timestamp="2024-10-19T18:35:22" failures="0" errors="0" skipped="1">
		<testcase classname="TestPawnshopApp" name="test_add_item" time="0.001" timestamp="2024-10-19T18:35:22" file="lab4\test_pawnshop.py" line="35"/>
		<testcase classname="TestPawnshopApp" name="test_delete_item" time="0.000" timestamp="2024-10-19T18:35:22" file="lab4\test_pawnshop.py" line="58"/>
		<testcase classname="TestPawnshopApp" name="test_get_item" time="0.000" timestamp="2024-10-19T18:35:22" file="lab4\test_pawnshop.py" line="24"/>
		<testcase classname="TestPawnshopApp" name="test_get_last_id" time="0.001" timestamp="2024-10-19T18:35:22" file="lab4\test_pawnshop.py" line="21"/>
		<testcase classname="TestPawnshopApp" name="test_show_items" time="0.002" timestamp="2024-10-19T18:35:22" file="lab4\test_pawnshop.py" line="67">
			<system-out><![CDATA[{'ціна': 500, 'назва': 'годинник'} id =  1
{'ціна': 300, 'назва': 'телефон'} id =  2
{'ціна': 400, 'назва': 'павербанк'} id =  3
]]></system-out>
		</testcase>
		<testcase classname="TestPawnshopApp" name="test_update_item" time="0.001" timestamp="2024-10-19T18:35:22" file="lab4\test_pawnshop.py" line="45"/>
		<testcase classname="TestPawnshopApp" name="test_failure" time="0.000" timestamp="2024-10-19T18:35:22" file="lab4\test_pawnshop.py" line="70">
			<skipped type="XFAIL" message="expected failure: (&lt;class 'AssertionError'&gt;, AssertionError('3 != 0'), &lt;traceback object at 0x00000201E323B100&gt;)"/>
		</testcase>
	</testsuite>
</testsuites>
